//
//  JKFoundation.h
//  JKCategories
//
//  Created by Jakey on 16/5/29.
//  Copyright © 2016年 www.skyfox.org. All rights reserved.
//

#ifndef JKFoundation_h
#define JKFoundation_h

#import "NSArray+CJGBlock.h"
#import "NSArray+CJGSafeAccess.h"
#import "NSBundle+CJGAppIcon.h"
#import "NSData+CJGAPNSToken.h"
#import "NSData+CJGBase64.h"
#import "NSData+CJGDataCache.h"
#import "NSData+CJGEncrypt.h"
#import "NSData+CJGGzip.h"
#import "NSData+CJGHash.h"
#import "NSData+CJGzlib.h"
#import "NSData+CJGPCM.h"
#import "NSDate+CJGCupertinoYankee.h"
#import "NSDate+CJGExtension.h"
#import "NSDate+CJGFormatter.h"
#import "NSDate+CJGInternetDateTime.h"
#import "NSDate+CJGReporting.h"
#import "NSDate+CJGUtilities.h"
#import "NSDateFormatter+CJGMake.h"
#import "NSDecimalNumber+CJGCalculatingByString.h"
#import "NSDecimalNumber+CJGExtensions.h"
#import "NSDictionary+CJGBlock.h"
#import "NSDictionary+CJGJSONString.h"
#import "NSDictionary+CJGMerge.h"
#import "NSDictionary+CJGSafeAccess.h"
#import "NSDictionary+CJGURL.h"
#import "NSDictionary+CJGXML.h"
#import "NSException+CJGTrace.h"
#import "NSFileHandle+CJGReadLine.h"
#import "NSFileManager+CJGPaths.h"
#import "NSHTTPCookieStorage+CJGFreezeDry.h"
#import "NSIndexPath+CJGOffset.h"
#import "NSInvocation+CJGBb.h"
#import "NSInvocation+CJGBlock.h"
#import "NSMutableURLRequest+CJGUpload.h"
#import "NSNotificationCenter+CJGMainThread.h"
#import "NSNumber+CJGCGFloat.h"
#import "NSNumber+CJGRomanNumerals.h"
#import "NSNumber+CJGRound.h"
#import "NSObject+CJGAddProperty.h"
#import "NSObject+CJGAppInfo.h"
#import "NSObject+CJGAssociatedObject.h"
#import "NSObject+CJGAutoCoding.h"
#import "NSObject+CJGBlocks.h"
#import "NSObject+CJGBlockTimer.h"
#import "NSObject+CJGEasyCopy.h"
#import "NSObject+CJGGCD.h"
#import "NSObject+CJGKVOBlocks.h"
#import "NSObject+CJGReflection.h"
#import "NSObject+CJGRuntime.h"
#import "NSRunLoop+CJGPerformBlock.h"
#import "NSSet+CJGBlock.h"
#import "NSString+CJGBase64.h"
#import "NSString+CJGContains.h"
#import "NSString+CJGDictionaryValue.h"
#import "NSString+CJGEmoji.h"
#import "NSString+CJGEncrypt.h"
#import "NSString+CJGHash.h"
#import "NSString+CJGMatcher.h"
#import "NSString+CJGMIME.h"
#import "NSString+CJGNormalRegex.h"
#import "NSString+CJGPinyin.h"
#import "NSString+CJGRemoveEmoji.h"
#import "NSString+CJGScore.h"
#import "NSString+CJGSize.h"
#import "NSString+CJGTrims.h"
#import "NSString+CJGURLEncode.h"
#import "NSString+CJGUUID.h"
#import "NSString+CJGXMLDictionary.h"
#import "NSString+CJGStringPages.h"
#import "NSTimer+CJGAddition.h"
#import "NSTimer+CJGBlocks.h"
#import "NSURL+CJGParam.h"
#import "NSURL+CJGQueryDictionary.h"
#import "NSURLConnection+CJGSelfSigned.h"
#import "NSURLRequest+CJGParamsFromDictionary.h"
#import "NSUserDefaults+CJGiCloudSync.h"
#import "NSUserDefaults+CJGSafeAccess.h"

#endif /* JKFoundation_h */
